package ui;

import entities.TournamentEntity;
import filing.InvalidFileExtensionException;
import filing.importer.Importer;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import jframeconfig.Config;
import tournaments.Tournament;
import java.io.File;
import ui.views.tournaments.ViewTournament;

public class TournamentsPage extends javax.swing.JFrame {
    
    TournamentEntity te = new TournamentEntity();
    String[] tblTournamentFields = {"Name", "Federation", "Director", "Rounds",
        "Type", "Start Date", "End Date"};
    Config cf = new Config();

    /**
     * Creates new form TournamentsPage
     */
    public TournamentsPage() {
        initComponents();
        cf.setAttributes(this, "Tournaments");

        //set up the table to hold the tournaments and makes it so cells arent editable
        DefaultTableModel model = new DefaultTableModel(tblTournamentFields, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        List<Tournament> tournaments = te.getAll();
        
        for (Tournament t : tournaments) {
            
            model.addRow(new Object[]{
                t.getName(),
                t.getFederation(),
                t.getDirector(),
                t.getRounds(),
                t.getTournamentType().getName(),
                t.getStartDate().format(Config.DTF),
                t.getEndDate().format(Config.DTF)
            });
        }
        
        tblTournaments.setModel(model);

        // help claude help me with this function -- makes it so when you 
        // double click the row, it'll take you to view the selected tournament
        // i researched how it works, it's like a way to 'instantiate'
        // abstract classes
        // pretty cool
        tblTournaments.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    int row = tblTournaments.getSelectedRow();
                    TournamentsPage.this.dispose();
                    new ViewTournament(tournaments.get(row)).setVisible(true);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lpnlTournamentPage = new javax.swing.JLayeredPane();
        spnlTable = new javax.swing.JScrollPane();
        tblTournaments = new javax.swing.JTable();
        btnHomeTab = new javax.swing.JButton();
        btnCreateTournament = new javax.swing.JButton();
        btnImportTournament = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblTournaments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spnlTable.setViewportView(tblTournaments);

        lpnlTournamentPage.add(spnlTable);
        spnlTable.setBounds(20, 200, 1280, 460);

        btnHomeTab.setFont(new java.awt.Font("UD Digi Kyokasho NK", 1, 24)); // NOI18N
        btnHomeTab.setText("Home");
        btnHomeTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeTabActionPerformed(evt);
            }
        });
        lpnlTournamentPage.setLayer(btnHomeTab, javax.swing.JLayeredPane.PALETTE_LAYER);
        lpnlTournamentPage.add(btnHomeTab);
        btnHomeTab.setBounds(540, 10, 230, 40);

        btnCreateTournament.setFont(new java.awt.Font("UD Digi Kyokasho NK", 1, 24)); // NOI18N
        btnCreateTournament.setText("Create");
        btnCreateTournament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateTournamentActionPerformed(evt);
            }
        });
        lpnlTournamentPage.setLayer(btnCreateTournament, javax.swing.JLayeredPane.PALETTE_LAYER);
        lpnlTournamentPage.add(btnCreateTournament);
        btnCreateTournament.setBounds(540, 120, 230, 40);

        btnImportTournament.setFont(new java.awt.Font("UD Digi Kyokasho NK", 1, 24)); // NOI18N
        btnImportTournament.setText("Import");
        btnImportTournament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportTournamentActionPerformed(evt);
            }
        });
        lpnlTournamentPage.setLayer(btnImportTournament, javax.swing.JLayeredPane.PALETTE_LAYER);
        lpnlTournamentPage.add(btnImportTournament);
        btnImportTournament.setBounds(790, 70, 230, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lpnlTournamentPage, javax.swing.GroupLayout.DEFAULT_SIZE, 1338, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lpnlTournamentPage, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeTabActionPerformed
        this.dispose();
        new ui.Main().setVisible(true);
    }//GEN-LAST:event_btnHomeTabActionPerformed

    private void btnCreateTournamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTournamentActionPerformed
        this.dispose();
        new ui.views.tournaments.CreateTournament().setVisible(true);
    }//GEN-LAST:event_btnCreateTournamentActionPerformed

    private void btnImportTournamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportTournamentActionPerformed
        // I kept getting an exception because my JFileChooser wasnt working
        // Apparently its something to do with my system and that there is a 
        // know error about it
        // So i had to ask AI to help me replicate something similar

        /*
        Heres the exception i kept getting: 
        Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:870)
	at java.base/java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:487)
	at java.base/java.util.ComparableTimSort.mergeForceCollapse(ComparableTimSort.java:426)
	at java.base/java.util.ComparableTimSort.sort(ComparableTimSort.java:222)
	at java.base/java.util.Arrays.sort(Arrays.java:1041)
	at java.desktop/sun.awt.shell.Win32ShellFolderManager2.get(Win32ShellFolderManager2.java:319)
	at java.desktop/sun.awt.shell.ShellFolder.get(ShellFolder.java:272)
	at java.desktop/sun.swing.plaf.synth.SynthFileChooserUIImpl$DirectoryComboBoxModel.addItem(SynthFileChooserUIImpl.java:770)
	at java.desktop/sun.swing.plaf.synth.SynthFileChooserUIImpl.doDirectoryChanged(SynthFileChooserUIImpl.java:563)
	at java.desktop/sun.swing.plaf.synth.SynthFileChooserUI$SynthFCPropertyChangeListener.propertyChange(SynthFileChooserUI.java:283)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:335)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8717)
	at java.desktop/javax.swing.JFileChooser.setCurrentDirectory(JFileChooser.java:610)
	at java.desktop/javax.swing.JFileChooser.<init>(JFileChooser.java:364)
	at java.desktop/javax.swing.JFileChooser.<init>(JFileChooser.java:310)
	at ui.tabbedPanels.TournamentsPage.btnImportTournamentActionPerformed(TournamentsPage.java:173)
	at ui.tabbedPanels.TournamentsPage$5.actionPerformed(TournamentsPage.java:135)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6621)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6386)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
         */
        
        // I left the comments it made so that i can understand what it was doing
        
        // 1. Force the file manager to look at a clean folder path to stop the crash loop
        System.setProperty("java.util.Arrays.useLegacyMergeSort", "true");

        // 2. Find the window that holds this page
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame parentFrame = null;
        if (parentWindow instanceof java.awt.Frame frame) {
            parentFrame = frame;
        }

        // 3. Open a native operating system file dialogue (Bypasses Synth entirely)
        java.awt.FileDialog fileDialog = new java.awt.FileDialog(parentFrame, "Import Tournament", java.awt.FileDialog.LOAD);

        // 4. (Optional) Set it to start in your current project folder instead of the glitched Desktop
        fileDialog.setDirectory(System.getProperty("user.dir"));

        //this has been done by me
        fileDialog.setIconImage(cf.getIcon().getImage());

        // 5. Make the dialog visible (this pauses execution until the user selects a file or cancels)
        fileDialog.setVisible(true);

        // 6. Grab the results safely
        String directory = fileDialog.getDirectory();
        String filename = fileDialog.getFile();
        
        if (directory != null && filename != null) {
            try {
                // This creates your final File object cleanly
                File file = new File(directory, filename);
                
                System.out.println("File loaded successfully: " + file.getAbsolutePath());

                // This part has been done by me.
                Importer im = new Importer(file);
                im.scanFile();
                Tournament t = im.getLoadedTournament();
                t.setIsImported(true);
                this.dispose();
                
                ui.views.tournaments.ViewTournament page = new ui.views.tournaments.ViewTournament(t);
                page.setImporter(im);
                page.setVisible(true);
                
            } catch (InvalidFileExtensionException ex) {
                System.out.println(ex.getMessage());
            }
        } else {
            System.out.println("User cancelled the file selection.");
        }
    }//GEN-LAST:event_btnImportTournamentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TournamentsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TournamentsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TournamentsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TournamentsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TournamentsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateTournament;
    private javax.swing.JButton btnHomeTab;
    private javax.swing.JButton btnImportTournament;
    private javax.swing.JLayeredPane lpnlTournamentPage;
    private javax.swing.JScrollPane spnlTable;
    private javax.swing.JTable tblTournaments;
    // End of variables declaration//GEN-END:variables
}
