
package ui.views.tournaments;

import enums.Federation;
import enums.PlayerTitle;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jframeconfig.Config;
import utils.Validation;
import players.Player;
import entities.PlayerEntity;

/**
 * Adds a manual player for the ConfigureTournament GUI 
 * @author tshim
 */
public class AddManualPlayer extends javax.swing.JFrame {
    private String tID;
    private PlayerEntity pe = new PlayerEntity();
    private DefaultTableModel model;
    private boolean isValid = false;
    
    /**
     * Creates new form AddManualPlayer
     * 
     * @param tID - the tournament id
     * @param model - the table model
     */
    public AddManualPlayer(String tID, DefaultTableModel model) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // used ai, didnt know how to stop it from exiting the entire application
        Config.setAttributes(this, "Add Manual Player to tournament");
        
        this.tID = tID;
        this.model = model;
        
        // adding player titles to cbox
        PlayerTitle[] titles = PlayerTitle.values();
        for(PlayerTitle title : titles){
            cBoxPT.addItem(title.getFullTitle());
        }
        
        
        // adding the federations to the combo box
        Federation[] fedValues = Federation.values();

        for (Federation fed : fedValues) {
            cBoxFed.addItem(fed.getCountryName());
        }

    }
    
    private String checkNameFields(){
        HashMap<String, String> fields = new HashMap<>();
        fields.put("First Name", txfFN.getText().trim());
        fields.put("Last Name", txfLN.getText().trim());
        fields.put("Fide ID", txfFID.getText().trim());
        
        return Validation.isValidStrings(fields);
    }
    
    private String checkDoubleFields(){
        HashMap<String, String> fields = new HashMap<>();
        fields.put("Rating", txfRating.getText());
        
        return Validation.isValidNumbers(fields, "double");
    }
    
    private void addPlayer(Player p) {
        if (pe.insert(p)) {

            model.addRow(new Object[]{
                p.getFullName(),
                p.getTitle(),
                p.getFideID(),
                p.getFederation(),
                p.getRating(),
                p.getScore(),
                p.getTieBreak()
            });
            
            System.out.println(p.getFullName() + " has been added to the tournament");
            this.dispose();
        }else {
            System.out.println("Unable to add player to the tournament");
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lpnlADM = new javax.swing.JLayeredPane();
        lblTName = new javax.swing.JLabel();
        lblTName1 = new javax.swing.JLabel();
        lblTName2 = new javax.swing.JLabel();
        lblTName3 = new javax.swing.JLabel();
        lblTName4 = new javax.swing.JLabel();
        lblTName5 = new javax.swing.JLabel();
        cBoxFed = new javax.swing.JComboBox<>();
        cBoxPT = new javax.swing.JComboBox<>();
        txfRating = new javax.swing.JTextField();
        txfLN = new javax.swing.JTextField();
        txfFN = new javax.swing.JTextField();
        txfFID = new javax.swing.JTextField();
        lblHeading = new javax.swing.JLabel();
        btnValidate = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        btnTournamentTab = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTName.setFont(new java.awt.Font("UD Digi Kyokasho NP", 0, 18)); // NOI18N
        lblTName.setText("Rating:");
        lpnlADM.add(lblTName);
        lblTName.setBounds(30, 470, 170, 40);

        lblTName1.setFont(new java.awt.Font("UD Digi Kyokasho NP", 0, 18)); // NOI18N
        lblTName1.setText("Last Name: ");
        lpnlADM.add(lblTName1);
        lblTName1.setBounds(30, 230, 150, 40);

        lblTName2.setFont(new java.awt.Font("UD Digi Kyokasho NP", 0, 18)); // NOI18N
        lblTName2.setText("Fide ID:");
        lpnlADM.add(lblTName2);
        lblTName2.setBounds(30, 290, 150, 40);

        lblTName3.setFont(new java.awt.Font("UD Digi Kyokasho NP", 0, 18)); // NOI18N
        lblTName3.setText("Title: ");
        lpnlADM.add(lblTName3);
        lblTName3.setBounds(30, 350, 140, 40);

        lblTName4.setFont(new java.awt.Font("UD Digi Kyokasho NP", 0, 18)); // NOI18N
        lblTName4.setText("Federation:");
        lpnlADM.add(lblTName4);
        lblTName4.setBounds(30, 410, 180, 40);

        lblTName5.setFont(new java.awt.Font("UD Digi Kyokasho NP", 0, 18)); // NOI18N
        lblTName5.setText("First Name:");
        lpnlADM.add(lblTName5);
        lblTName5.setBounds(30, 170, 150, 40);

        cBoxFed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        cBoxFed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxFedActionPerformed(evt);
            }
        });
        lpnlADM.add(cBoxFed);
        cBoxFed.setBounds(270, 410, 340, 40);

        cBoxPT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        cBoxPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxPTActionPerformed(evt);
            }
        });
        lpnlADM.add(cBoxPT);
        cBoxPT.setBounds(270, 350, 340, 40);
        lpnlADM.add(txfRating);
        txfRating.setBounds(270, 470, 340, 40);
        lpnlADM.add(txfLN);
        txfLN.setBounds(270, 230, 340, 40);
        lpnlADM.add(txfFN);
        txfFN.setBounds(270, 170, 340, 40);
        lpnlADM.add(txfFID);
        txfFID.setBounds(270, 290, 340, 40);

        lblHeading.setFont(new java.awt.Font("UD Digi Kyokasho NP", 1, 18)); // NOI18N
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("Manually Add Player");
        lpnlADM.add(lblHeading);
        lblHeading.setBounds(430, 30, 429, 40);

        btnValidate.setText("Validate Form");
        btnValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidateActionPerformed(evt);
            }
        });
        lpnlADM.add(btnValidate);
        btnValidate.setBounds(1000, 410, 220, 50);

        btnSubmit.setText("Register Player");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        lpnlADM.add(btnSubmit);
        btnSubmit.setBounds(1000, 480, 220, 50);

        btnTournamentTab.setFont(new java.awt.Font("UD Digi Kyokasho NK", 1, 24)); // NOI18N
        btnTournamentTab.setText("Go Back");
        btnTournamentTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTournamentTabActionPerformed(evt);
            }
        });
        lpnlADM.setLayer(btnTournamentTab, javax.swing.JLayeredPane.PALETTE_LAYER);
        lpnlADM.add(btnTournamentTab);
        btnTournamentTab.setBounds(1080, 20, 230, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lpnlADM, javax.swing.GroupLayout.DEFAULT_SIZE, 1338, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lpnlADM, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cBoxFedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxFedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBoxFedActionPerformed

    private void cBoxPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxPTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBoxPTActionPerformed

    private void btnValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidateActionPerformed
        String sErrors = checkNameFields(), dErrors = checkDoubleFields(), errors = "";
        
        if(!sErrors.isBlank()) errors += sErrors;
        if(!dErrors.isBlank()) errors += dErrors;
        
        if(errors.isBlank()){
            isValid = true;
            JOptionPane.showMessageDialog(this, "All fields are valid.");
        } else {
            JOptionPane.showMessageDialog(this, errors);
        }
    }//GEN-LAST:event_btnValidateActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if (!isValid) {
            String v = "Form is not yet valid/validated.";
            System.out.println(v);
            JOptionPane.showMessageDialog(this, v);
        } else {
            Player p = new Player();
            p.setTournamentID(tID);
            p.setFirstName(txfFN.getText().trim());
            p.setLastName(txfLN.getText().trim());
            p.setFideID(txfFID.getText().trim());
            p.setRating(Double.parseDouble(txfRating.getText().trim()));
            p.setTitle(PlayerTitle.getTitleFromRating(p.getRating()));
            p.setFederation(Federation.getValueFromName((String) cBoxFed.getSelectedItem()).name());
            
            addPlayer(p);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnTournamentTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTournamentTabActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnTournamentTabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddManualPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddManualPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddManualPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddManualPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddManualPlayer(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnTournamentTab;
    private javax.swing.JButton btnValidate;
    private javax.swing.JComboBox<String> cBoxFed;
    private javax.swing.JComboBox<String> cBoxPT;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblTName;
    private javax.swing.JLabel lblTName1;
    private javax.swing.JLabel lblTName2;
    private javax.swing.JLabel lblTName3;
    private javax.swing.JLabel lblTName4;
    private javax.swing.JLabel lblTName5;
    private javax.swing.JLayeredPane lpnlADM;
    private javax.swing.JTextField txfFID;
    private javax.swing.JTextField txfFN;
    private javax.swing.JTextField txfLN;
    private javax.swing.JTextField txfRating;
    // End of variables declaration//GEN-END:variables
}
