/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.views.tournaments;

import entities.PlayerEntity;
import entities.TournamentEntity;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jframeconfig.Config;
import players.Player;
import tournaments.Tournament;

/**
 *
 * @author tshim
 */
public class ConfigureTournament extends javax.swing.JFrame {

    private static String tID;
    private final TournamentEntity TE = new TournamentEntity();
    private final PlayerEntity PE = new PlayerEntity();
    private Tournament t;
    private final DefaultTableModel MODEL = new DefaultTableModel();

    /**
     * Creates new form ConfigureTournament
     */
    public ConfigureTournament(String tID) {
        this.tID = tID;
        initComponents();
        Config.setAttributes(this, "Configure Tournament");
        t = TE.find(tID);

        txfNumPlayers.setText(tblPlayers.getRowCount() + "");

        String[] playerFields = {"Full Name", "Title", "Fide ID", "Federation",
            "Rating", "Score", "Tiebreak"};

        MODEL.setColumnIdentifiers(playerFields);

        tblPlayers.setModel(MODEL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumPlayers = new javax.swing.JLabel();
        lblHeading = new javax.swing.JLabel();
        txfNumPlayers = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlayers = new javax.swing.JTable();
        lblHeading1 = new javax.swing.JLabel();
        btnGPlayer = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        btnGenManualPlayer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblNumPlayers.setFont(new java.awt.Font("UD Digi Kyokasho NP", 0, 18)); // NOI18N
        lblNumPlayers.setText("Number of Players:");
        getContentPane().add(lblNumPlayers);
        lblNumPlayers.setBounds(50, 126, 250, 30);

        lblHeading.setFont(new java.awt.Font("UD Digi Kyokasho NP", 1, 18)); // NOI18N
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("Configure Tournament");
        getContentPane().add(lblHeading);
        lblHeading.setBounds(430, 30, 429, 40);

        txfNumPlayers.setEditable(false);
        txfNumPlayers.setFont(new java.awt.Font("UD Digi Kyokasho NP", 0, 18)); // NOI18N
        txfNumPlayers.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfNumPlayers.setText("0");
        getContentPane().add(txfNumPlayers);
        txfNumPlayers.setBounds(276, 113, 90, 50);

        tblPlayers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblPlayers.setColumnSelectionAllowed(true);
        tblPlayers.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblPlayersPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblPlayers);
        tblPlayers.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(490, 130, 825, 523);

        lblHeading1.setFont(new java.awt.Font("UD Digi Kyokasho NP", 1, 12)); // NOI18N
        lblHeading1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading1.setText("Tournament Players");
        getContentPane().add(lblHeading1);
        lblHeading1.setBounds(790, 100, 230, 28);

        btnGPlayer.setText("Generate Player");
        btnGPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGPlayerActionPerformed(evt);
            }
        });
        getContentPane().add(btnGPlayer);
        btnGPlayer.setBounds(170, 250, 219, 36);

        btnSubmit.setText("Go to Tournament Rounds");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit);
        btnSubmit.setBounds(120, 530, 260, 42);

        btnGenManualPlayer.setText("Manually Add Player");
        btnGenManualPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenManualPlayerActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenManualPlayer);
        btnGenManualPlayer.setBounds(170, 200, 220, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGPlayerActionPerformed
        Player p = Player.generatePlayer();
        p.setTournamentID(tID);

        addPlayer(p);

        txfNumPlayers.setText(tblPlayers.getRowCount() + "");
        System.out.println("Added a player to the tournament.");
    }//GEN-LAST:event_btnGPlayerActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if (tblPlayers.getRowCount() >= 2) {
            this.dispose();
            new TournamentRounds(t).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Your tournament has to have at least 2 players");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnGenManualPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenManualPlayerActionPerformed
        AddManualPlayer adm = new AddManualPlayer(t.getId(), MODEL);

        // this listener is AI assisted. Wanted to ensure that the txf updates when a manual player is added
        adm.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                System.out.println("Adding manual player done.");
                txfNumPlayers.setText(String.valueOf(MODEL.getRowCount()));
            }
        });

        adm.setVisible(true);
    }//GEN-LAST:event_btnGenManualPlayerActionPerformed

    private void tblPlayersPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblPlayersPropertyChange

    }//GEN-LAST:event_tblPlayersPropertyChange

    private void addPlayer(Player p) {
        if (PE.insert(p)) {

            MODEL.addRow(new Object[]{
                p.getFullName(),
                p.getTitle(),
                p.getFideID(),
                p.getFederation(),
                p.getRating(),
                p.getScore(),
                p.getTieBreak()
            });

            System.out.println(p.getFullName() + " has been added to the tournament");
        } else {
            System.out.println("Unable to add player to the tournament");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigureTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigureTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigureTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigureTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigureTournament(tID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGPlayer;
    private javax.swing.JButton btnGenManualPlayer;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblHeading1;
    private javax.swing.JLabel lblNumPlayers;
    private javax.swing.JTable tblPlayers;
    private javax.swing.JTextField txfNumPlayers;
    // End of variables declaration//GEN-END:variables
}
