/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.views.tournaments;

import entities.PlayerEntity;
import entities.TournamentEntity;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import matchmaking.MatchMaker;
import players.Player;
import tournaments.Tournament;
import database.PlayerFields;
import entities.GameEntity;
import games.Game;
import java.util.HashMap;
import javax.swing.JOptionPane;
import jframeconfig.Config;

/**
 *
 * @author tshim
 */
public class TournamentRounds extends javax.swing.JFrame {

    private final TournamentEntity TE = new TournamentEntity();
    private final PlayerEntity PE = new PlayerEntity();
    private final GameEntity GE = new GameEntity();
    private Tournament t;
    private final DefaultTableModel MODEL = new DefaultTableModel();
    private MatchMaker mm;
    private int currRound = 1, maxRounds;
    private List<List<Game>> gamesForEachRound = new ArrayList<>(new ArrayList<>());

    /**
     * Creates new form TournamentRounds
     */
    public TournamentRounds(Tournament t) {
        initComponents();
        Config.setAttributes(this, "Tournament Rounds");

        this.t = t;

        // set the players who registered into the tournament from the database
        setRegisteredPlayers();

        lblHeading.setText(t.getName());
        maxRounds = t.getRounds();

        // initialise the matchmaker
        initMatchMaker();
        
        // set round combo box items
        
        for (int i = currRound; i <= maxRounds; i++) {
            cBoxRound.addItem(i);
        }
    }

    private void doRound() {
        if (currRound <= maxRounds) {
            gamesForEachRound.add(mm.generateRound(t));

            currRound++;
            mm.setRound(currRound);
        } else {
            String s = "Tournament has already reached the maximum amount of rounds. This cannot be changed.";
            System.out.println(s);
            JOptionPane.showMessageDialog(this, "s");
            
            HashMap<String, Object> attrs = new HashMap<>();
            attrs.put("has_ended", true);
            
            t = TE.update(t.getId(), attrs);
            t.setPlayers(mm.getLeaderBoard());
        }
    }

    private void setRegisteredPlayers() {
        List<Player> players = new ArrayList<>();

        List<HashMap<String, Object>> ps = PE.selectWhere(PlayerFields.TOURNAMENT_ID, "=", t.getId());

        if (!ps.isEmpty()) {
            for (HashMap<String, Object> playerRow : ps) {
                players.add(PE.mapRow(playerRow));
            }
            t.setPlayers(players);
        } else {
            System.out.println("No registered players in this tournament.");
            JOptionPane.showMessageDialog(this, "This tournament does not have enough players.");
        }

    }

    private void initMatchMaker() {
        mm = new MatchMaker(t.getPlayers(), currRound);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lpnlTR = new javax.swing.JLayeredPane();
        btnHomeTab = new javax.swing.JButton();
        btnTournamentTab = new javax.swing.JButton();
        lblHeading = new javax.swing.JLabel();
        cBoxRound = new javax.swing.JComboBox<>();
        lblHeading1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnHomeTab.setFont(new java.awt.Font("UD Digi Kyokasho NK", 1, 24)); // NOI18N
        btnHomeTab.setText("Home");
        btnHomeTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeTabActionPerformed(evt);
            }
        });

        btnTournamentTab.setFont(new java.awt.Font("UD Digi Kyokasho NK", 1, 24)); // NOI18N
        btnTournamentTab.setText("Tournaments");
        btnTournamentTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTournamentTabActionPerformed(evt);
            }
        });

        lblHeading.setFont(new java.awt.Font("UD Digi Kyokasho NP", 1, 18)); // NOI18N
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cBoxRound.setModel(new javax.swing.DefaultComboBoxModel<>(new int[] {}));
        cBoxRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxRoundActionPerformed(evt);
            }
        });

        lblHeading1.setFont(new java.awt.Font("UD Digi Kyokasho NP", 1, 14)); // NOI18N
        lblHeading1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading1.setText("Select Round.");

        lpnlTR.setLayer(btnHomeTab, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnlTR.setLayer(btnTournamentTab, javax.swing.JLayeredPane.PALETTE_LAYER);
        lpnlTR.setLayer(lblHeading, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnlTR.setLayer(cBoxRound, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnlTR.setLayer(lblHeading1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lpnlTRLayout = new javax.swing.GroupLayout(lpnlTR);
        lpnlTR.setLayout(lpnlTRLayout);
        lpnlTRLayout.setHorizontalGroup(
            lpnlTRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpnlTRLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnHomeTab, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252)
                .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 353, Short.MAX_VALUE)
                .addComponent(btnTournamentTab, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(lpnlTRLayout.createSequentialGroup()
                .addGroup(lpnlTRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lpnlTRLayout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(cBoxRound, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lpnlTRLayout.createSequentialGroup()
                        .addGap(555, 555, 555)
                        .addComponent(lblHeading1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lpnlTRLayout.setVerticalGroup(
            lpnlTRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpnlTRLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(lpnlTRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHomeTab, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTournamentTab, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHeading1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(cBoxRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(575, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lpnlTR)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lpnlTR)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeTabActionPerformed
        this.dispose();
        new ui.Main().setVisible(true);
    }//GEN-LAST:event_btnHomeTabActionPerformed

    private void btnTournamentTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTournamentTabActionPerformed
        this.dispose();
        new ui.tabbedPanels.TournamentsPage().setVisible(true);
    }//GEN-LAST:event_btnTournamentTabActionPerformed

    private void cBoxRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxRoundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBoxRoundActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TournamentRounds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TournamentRounds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TournamentRounds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TournamentRounds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TournamentRounds(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHomeTab;
    private javax.swing.JButton btnTournamentTab;
    private javax.swing.JComboBox<String> cBoxRound;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblHeading1;
    private javax.swing.JLayeredPane lpnlTR;
    // End of variables declaration//GEN-END:variables
}
