package ui.views.tournaments;

import entities.TournamentEntity;
import filing.importer.Importer;
import games.Game;
import java.util.List;
import jframeconfig.Config;
import players.Player;
import tournaments.*;

public class ViewTournament extends javax.swing.JFrame {

    private final Tournament t;
    private final Config cf = new Config();
    private Importer importer;

    /**
     * Creates new form ViewTournaments
     *
     * @param tournament
     */
    public ViewTournament(Tournament tournament) {
        initComponents();
        this.t = tournament;
        
        cf.setAttributes(this, tournament.getName());
        lblHeading.setText(t.getName());

        // if the tournament is imported, then create the save button,
        // and set the tournament stats lbls since you don't need to
        // get the games from the database
        if (t.getIsImported()) {
            setTournamentStats();

            javax.swing.JButton btnSave = btnViewGames;
            btnSave.setSize(WIDTH, HEIGHT);
            btnSave.setText("Save To Database");
            btnSave.setLocation(btnViewGames.getX(), btnViewGames.getY() - 1000);
            btnSave.setFont(new java.awt.Font("UD Digi Kyokasho NK", 1, 18));
            btnSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

            btnSave.addActionListener((java.awt.event.ActionEvent evt) -> {
                btnSaveActionPerformed(evt, btnSave);
            });

        } else {
            t.setGamesFromDB();
            setTournamentStats();
        }
    }

    public void setTournamentStats() {
        List<Game> games = t.getGames();
        List<Player> players = t.getLeaderBoard();

        int numGames = games.size(), numPlayers = players.size(),
                numNoDraws = 0, numDraws = 0;
        double drawPercentage, aveRating, sumRating = 0;

        if (numGames == 0) {
            lblAverageRating.setText("Not Available");
            lblDrawPercentage.setText("Not Available");
            lblNumPlayers.setText("Not Available");
            lblTotalGames.setText("No Games were found");
            lblNumNoDraws.setText("Not Available");
            return;
        }

        for (Game g : games) {
            if (g.isDraw()) {
                numDraws++;
            }
        }

        numNoDraws = numGames - numDraws;
        drawPercentage = Double.parseDouble(String.format("%.2f", (double) (numDraws / numGames * 100)));

        for (Player p : players) {
            sumRating += p.getRating();
        }

        aveRating = Double.parseDouble(String.format("%.2f", (double) (sumRating / numPlayers)));

        // Set the stats
        lblAverageRating.setText(String.format("Average Rating: %.2f", aveRating));
        lblDrawPercentage.setText(String.format("Draw Percentage: %.2f%%", drawPercentage));
        lblNumPlayers.setText(String.format("Number of Players: %d", numPlayers));
        lblTotalGames.setText(String.format("Total Games: %d", numGames));
        lblNumNoDraws.setText(String.format("Number of Decisive Games: %d", numNoDraws));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lpnlVT = new javax.swing.JLayeredPane();
        lblPOTT = new javax.swing.JLabel();
        btnHomeTab = new javax.swing.JButton();
        btnTournamentTab = new javax.swing.JButton();
        lblHeading = new javax.swing.JLabel();
        btnViewGames = new javax.swing.JButton();
        lblStats = new javax.swing.JLabel();
        lblNumPlayers = new javax.swing.JLabel();
        lblTotalGames = new javax.swing.JLabel();
        lblNumNoDraws = new javax.swing.JLabel();
        lblDrawPercentage = new javax.swing.JLabel();
        lblAverageRating = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPOTT.setFont(new java.awt.Font("UD Digi Kyokasho NK", 1, 18)); // NOI18N
        lblPOTT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPOTT.setText("Player of the Tournament");

        btnHomeTab.setFont(new java.awt.Font("UD Digi Kyokasho NK", 1, 24)); // NOI18N
        btnHomeTab.setText("Home");
        btnHomeTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeTabActionPerformed(evt);
            }
        });

        btnTournamentTab.setFont(new java.awt.Font("UD Digi Kyokasho NK", 1, 24)); // NOI18N
        btnTournamentTab.setText("Tournaments");
        btnTournamentTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTournamentTabActionPerformed(evt);
            }
        });

        lblHeading.setFont(new java.awt.Font("UD Digi Kyokasho NK", 1, 24)); // NOI18N
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnViewGames.setFont(new java.awt.Font("UD Digi Kyokasho NK", 1, 24)); // NOI18N
        btnViewGames.setText("View Games");
        btnViewGames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewGamesActionPerformed(evt);
            }
        });

        lblStats.setFont(new java.awt.Font("UD Digi Kyokasho NK", 1, 18)); // NOI18N
        lblStats.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStats.setText("Statistics");

        lblNumPlayers.setFont(new java.awt.Font("UD Digi Kyokasho NK", 1, 14)); // NOI18N
        lblNumPlayers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNumPlayers.setText("Statistics");

        lblTotalGames.setFont(new java.awt.Font("UD Digi Kyokasho NK", 1, 14)); // NOI18N
        lblTotalGames.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalGames.setText("Statistics");

        lblNumNoDraws.setFont(new java.awt.Font("UD Digi Kyokasho NK", 1, 14)); // NOI18N
        lblNumNoDraws.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNumNoDraws.setText("Statistics");

        lblDrawPercentage.setFont(new java.awt.Font("UD Digi Kyokasho NK", 1, 14)); // NOI18N
        lblDrawPercentage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDrawPercentage.setText("Statistics");

        lblAverageRating.setFont(new java.awt.Font("UD Digi Kyokasho NK", 1, 14)); // NOI18N
        lblAverageRating.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAverageRating.setText("Statistics");

        lpnlVT.setLayer(lblPOTT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnlVT.setLayer(btnHomeTab, javax.swing.JLayeredPane.PALETTE_LAYER);
        lpnlVT.setLayer(btnTournamentTab, javax.swing.JLayeredPane.PALETTE_LAYER);
        lpnlVT.setLayer(lblHeading, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnlVT.setLayer(btnViewGames, javax.swing.JLayeredPane.PALETTE_LAYER);
        lpnlVT.setLayer(lblStats, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnlVT.setLayer(lblNumPlayers, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnlVT.setLayer(lblTotalGames, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnlVT.setLayer(lblNumNoDraws, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnlVT.setLayer(lblDrawPercentage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpnlVT.setLayer(lblAverageRating, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lpnlVTLayout = new javax.swing.GroupLayout(lpnlVT);
        lpnlVT.setLayout(lpnlVTLayout);
        lpnlVTLayout.setHorizontalGroup(
            lpnlVTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lpnlVTLayout.createSequentialGroup()
                .addGroup(lpnlVTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(lpnlVTLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnHomeTab, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTournamentTab, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lpnlVTLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblStats, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                        .addComponent(btnViewGames, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217)
                        .addComponent(lblPOTT, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, lpnlVTLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(lpnlVTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNumPlayers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalGames, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumNoDraws, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDrawPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAverageRating, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(56, 56, 56))
        );
        lpnlVTLayout.setVerticalGroup(
            lpnlVTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpnlVTLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(lpnlVTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHomeTab, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTournamentTab, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(lpnlVTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPOTT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewGames, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStats, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(lblNumPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblTotalGames, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblNumNoDraws, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblDrawPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblAverageRating, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lpnlVT)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lpnlVT)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeTabActionPerformed
        this.dispose();
        new ui.Main().setVisible(true);
    }//GEN-LAST:event_btnHomeTabActionPerformed

    private void btnTournamentTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTournamentTabActionPerformed
        this.dispose();
        new ui.tabbedPanels.TournamentsPage().setVisible(true);
    }//GEN-LAST:event_btnTournamentTabActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt, javax.swing.JButton btn) {
        if (importer.saveToDB()) {
            btn.setVisible(false);
        }
    }


    private void btnViewGamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewGamesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewGamesActionPerformed

    public void setImporter(Importer im) {
        importer = im;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTournament(new Tournament()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHomeTab;
    private javax.swing.JButton btnTournamentTab;
    private javax.swing.JButton btnViewGames;
    private javax.swing.JLabel lblAverageRating;
    private javax.swing.JLabel lblDrawPercentage;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblNumNoDraws;
    private javax.swing.JLabel lblNumPlayers;
    private javax.swing.JLabel lblPOTT;
    private javax.swing.JLabel lblStats;
    private javax.swing.JLabel lblTotalGames;
    private javax.swing.JLayeredPane lpnlVT;
    // End of variables declaration//GEN-END:variables
}
